#!/bin/bash

NC="\e[0m"
SUCCESS="\e[42m"
WARNING="\e[43m"
ERROR="\e[41m"

if [ "$1" == "checkout" ] || [ "$1" == "c" ]; then
    ./develop install

    echo -e "${SUCCESS}Checkout finished${NC}"
elif [ "$1" == "install" ]; then
    composer install

    echo -e "${SUCCESS}Installation finished${NC}"
elif [ "$1" == "update" ]; then
    composer update

    echo -e "${SUCCESS}Update finished${NC}"
else
    echo -e "${WARNING}No option specified${NC}"
fi
