version: '3.8'

services:
  php_nepflix:
    hostname: nepflix
    build: docker/php/.
    image: php_nepflix:apache
    container_name: php_nepflix
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - docker_server_caddy
      - docker_server_database
    ports:
      - "${HTTP_PORT}:80"

networks:
  docker_server_caddy:
    external: true
  docker_server_database:
    external: true