version: '3.8'

services:
  php_nepflix:
    hostname: nepflix
    build: docker/php/.
    image: php_nepflix:apache
    container_name: php_nepflix
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - caddy_net
    ports:
      - "${HTTP_PORT}:80"

networks:
  caddy_net:
    external: true